
-- 이벤트 리스트 뷰

CREATE VIEW V_EVENT_LIST AS
SELECT e.EVENT_NO, e.EVT_TITLE, e.MEM_ID, e.EVT_WRITE_DAY, e.EVT_HITS, 
NVL((SELECT COUNT(re.EVENT_RE_NO) FROM TB_EVENT_RE re WHERE re.EVT_NO = 
e.EVENT_NO AND re.EVT_RE_DEL_CHECK = 0), 0) as count_re
FROM TB_EVENT e LEFT OUTER JOIN TB_EVENT_RE r
ON (e.EVENT_NO = r.EVT_NO)
WHERE e.EVT_DEL_CHECK =0 
GROUP BY e.EVENT_NO, e.EVT_TITLE, e.MEM_ID, e.EVT_WRITE_DAY, e.EVT_HITS
ORDER BY e.EVENT_NO DESC;


-- 