------------------------------------------------------------------ product
INSERT INTO tb_product (product_no, product_name, selling_price, cost_price, stock, display_state, sale_state, represent_img, detail_img, summary_ex, detail_ex, deleted_state, weight, category_cd) VALUES (PRODUCT_NO_SEQ.NEXTVAL,'아마씨 비누',3500.0,3000.0,100.0,1.0,1.0,'http://i.imgur.com/XQxOgR0.jpg','http://naturalmom.co.kr/shop/shop_image/attach/1508/20150825103458_dssxswyt.jpg','영양 가득한 생명의 씨앗','null',0.0,100.0,1.0);
INSERT INTO tb_product (product_no, product_name, selling_price, cost_price, stock, display_state, sale_state, represent_img, detail_img, summary_ex, detail_ex, deleted_state, weight, category_cd) VALUES (PRODUCT_NO_SEQ.NEXTVAL,'붉나무비누',5500.0,4000.0,50.0,1.0,1.0,'http://i.imgur.com/bR5YMhA.jpg','http://naturalmom.co.kr/shop/shop_image/attach/1512/20151208104114_pmlnirpn.jpg','건강하고 생기있는 살결을 위해','null',0.0,90.0,2.0);
INSERT INTO tb_product (product_no, product_name, selling_price, cost_price, stock, display_state, sale_state, represent_img, detail_img, summary_ex, detail_ex, deleted_state, weight, category_cd) VALUES (PRODUCT_NO_SEQ.NEXTVAL,'뽕잎 비누',4300.0,3500.0,100.0,1.0,1.0,'http://i.imgur.com/BgjzGXR.jpg','http://naturalmom.co.kr/shop/shop_image/attach/1512/20151207144609_iumbvwrf.jpg','맑은 피부톤을 위한','null',0.0,90.0,3.0);
INSERT INTO tb_product (product_no, product_name, selling_price, cost_price, stock, display_state, sale_state, represent_img, detail_img, summary_ex, detail_ex, deleted_state, weight, category_cd) VALUES (PRODUCT_NO_SEQ.NEXTVAL,'쑥 비누',4300.0,3500.0,100.0,1.0,1.0,'http://i.imgur.com/ELZ9gpf.jpg','http://naturalmom.co.kr/shop/shop_image/attach/1512/20151207143314_qsuwwiwa.jpg','풍부한 무기질과 비타민의','null',0.0,90.0,4.0);
INSERT INTO tb_product (product_no, product_name, selling_price, cost_price, stock, display_state, sale_state, represent_img, detail_img, summary_ex, detail_ex, deleted_state, weight, category_cd) VALUES (PRODUCT_NO_SEQ.NEXTVAL,'발효어성초 비누',4500.0,3500.0,100.0,1.0,1.0,'http://i.imgur.com/feTTLKa.jpg','http://naturalmom.co.kr/shop/shop_image/attach/1512/20151204180910_lzlepvxk.jpg','지성 피부를 위한','null',1.0,90.0,1.0);
INSERT INTO tb_product (product_no, product_name, selling_price, cost_price, stock, display_state, sale_state, represent_img, detail_img, summary_ex, detail_ex, deleted_state, weight, category_cd) VALUES (PRODUCT_NO_SEQ.NEXTVAL,'로즈마리 비누',4500.0,3500.0,100.0,0.0,0.0,'http://i.imgur.com/ypYvxLI.jpg','http://naturalmom.co.kr/shop/shop_image/attach/1512/20151204175539_xutysnbt.jpg','보습 및 피부 탄력을 위한','null',0.0,90.0,2.0);
INSERT INTO tb_product (product_no, product_name, selling_price, cost_price, stock, display_state, sale_state, represent_img, detail_img, summary_ex, detail_ex, deleted_state, weight, category_cd) VALUES (PRODUCT_NO_SEQ.NEXTVAL,'감초 비누',3900.0,3000.0,100.0,1.0,0.0,'http://i.imgur.com/KDQB1fW.jpg','http://naturalmom.co.kr/shop/shop_image/attach/1512/20151204174731_wwpgotcr.jpg','민감한 살결에 좋은','null',0.0,90.0,3.0);
INSERT INTO tb_product (product_no, product_name, selling_price, cost_price, stock, display_state, sale_state, represent_img, detail_img, summary_ex, detail_ex, deleted_state, weight, category_cd) VALUES (PRODUCT_NO_SEQ.NEXTVAL,'편백나무 비누',4300.0,3500.0,100.0,0.0,1.0,'http://i.imgur.com/K69YdaC.jpg','http://naturalmom.co.kr/shop/shop_image/attach/1512/20151204141945_tmhwnaho.jpg','피톤치드가 함유되어 있는','null',0.0,90.0,4.0);



-------------------------------------------------------------------- order
INSERT INTO tb_order (order_no, order_date, charge, credit_num, credit_exp, rcv_name, rcv_phone, rcv_addr_post, rcv_addr_detail, delivery_msg, tracking_num, credit_cd, delivery_com_cd, mem_id) VALUES (ORDER_NO_SEQ.NEXTVAL,SYSDATE,3900.0,'1234123412341234','1901','이수진','010-2222-2222','111-221','경기도 안산시 안산구 안산3동 안산아파트 403동 101호','배송전 연락바람',0.0,10.0,4.0,'soojin');
INSERT INTO tb_order (order_no, order_date, charge, credit_num, credit_exp, rcv_name, rcv_phone, rcv_addr_post, rcv_addr_detail, delivery_msg, tracking_num, credit_cd, delivery_com_cd, mem_id) VALUES (ORDER_NO_SEQ.NEXTVAL,SYSDATE,9000.0,'1234123412341234','1901','최소라','010-1111-1111','111-222','서울시 광진구 구의2동 구의아파트 101동 202호','무인택배함에 넣어주세요',0.0,10.0,4.0,'sora');
INSERT INTO tb_order (order_no, order_date, charge, credit_num, credit_exp, rcv_name, rcv_phone, rcv_addr_post, rcv_addr_detail, delivery_msg, tracking_num, credit_cd, delivery_com_cd, mem_id) VALUES (ORDER_NO_SEQ.NEXTVAL,SYSDATE,8600.0,'1234123412341234','1901','이수진','010-2222-2222','111-223','경기도 안산시 안산구 안산3동 안산아파트 403동 101호','배송전 연락바람',0.0,13.0,4.0,'soojin');
INSERT INTO tb_order (order_no, order_date, charge, credit_num, credit_exp, rcv_name, rcv_phone, rcv_addr_post, rcv_addr_detail, delivery_msg, tracking_num, credit_cd, delivery_com_cd, mem_id) VALUES (ORDER_NO_SEQ.NEXTVAL,SYSDATE,5500.0,'1234123412341234','1901','윤수민','010-0000-0000','111-224','서울시 강동구 강동3동 강동아파트 102동 202호','빨리 갖다주세요 현기증나요',0.0,17.0,4.0,'soomin');
INSERT INTO tb_order (order_no, order_date, charge, credit_num, credit_exp, rcv_name, rcv_phone, rcv_addr_post, rcv_addr_detail, delivery_msg, tracking_num, credit_cd, delivery_com_cd, mem_id) VALUES (ORDER_NO_SEQ.NEXTVAL,SYSDATE,5500.0,'1234123412341234','1901','윤수민','010-0000-0000','111-225','서울시 강동구 강동3동 강동아파트 102동 202호','빨리 갖다주세요 현기증나요',0.0,17.0,4.0,'soomin');
INSERT INTO tb_order (order_no, order_date, charge, credit_num, credit_exp, rcv_name, rcv_phone, rcv_addr_post, rcv_addr_detail, delivery_msg, tracking_num, credit_cd, delivery_com_cd, mem_id) VALUES (ORDER_NO_SEQ.NEXTVAL,SYSDATE,10500.0,'1234123412341234','1901','최소라','010-1111-1111','111-226','서울시 광진구 구의2동 구의아파트 101동 202호','무인택배함에 넣어주세요',0.0,11.0,4.0,'sora');
INSERT INTO tb_order (order_no, order_date, charge, credit_num, credit_exp, rcv_name, rcv_phone, rcv_addr_post, rcv_addr_detail, delivery_msg, tracking_num, credit_cd, delivery_com_cd, mem_id) VALUES (ORDER_NO_SEQ.NEXTVAL,SYSDATE,3500.0,'1234123412341234','1901','최민희','010-3333-3333','111-227','경기도 남양주시 양주동 남양주아파트 303동 202호','미니미니 택배왔숑',0.0,16.0,4.0,'minhee');
INSERT INTO tb_order (order_no, order_date, charge, credit_num, credit_exp, rcv_name, rcv_phone, rcv_addr_post, rcv_addr_detail, delivery_msg, tracking_num, credit_cd, delivery_com_cd, mem_id) VALUES (ORDER_NO_SEQ.NEXTVAL,SYSDATE,4300.0,'1234123412341234','1901','최소라','010-1111-1111','111-228','서울시 광진구 구의2동 구의아파트 101동 202호','무인택배함에 넣어주세요',0.0,11.0,4.0,'sora');



-------------------------------------------------------------------- product_n_order
INSERT INTO tb_product_n_order (product_no, order_no, buy_num,  process_cd) VALUES (10006.0,10000,1.0,11);
INSERT INTO tb_product_n_order (product_no, order_no, buy_num,  process_cd) VALUES (10004.0,10001,2.0,12);
INSERT INTO tb_product_n_order (product_no, order_no, buy_num,  process_cd) VALUES (10003.0,10002,2.0,13);
INSERT INTO tb_product_n_order (product_no, order_no, buy_num,  process_cd) VALUES (10001.0,10003,1.0,14);
INSERT INTO tb_product_n_order (product_no, order_no, buy_num,  process_cd) VALUES (10001.0,10004,1.0,14);
INSERT INTO tb_product_n_order (product_no, order_no, buy_num,  process_cd) VALUES (10000.0,10005,3.0,21);
INSERT INTO tb_product_n_order (product_no, order_no, buy_num,  process_cd) VALUES (10000.0,10006,1.0,31);
INSERT INTO tb_product_n_order (product_no, order_no, buy_num,  process_cd) VALUES (10002.0,10007,1.0,32);



-------------------------------------------------------------------- event
INSERT INTO tb_event (event_no, evt_title, evt_write_day, evt_hits, evt_content, evt_del_check, board_id, mem_id) VALUES (EVENT_NO_SEQ.nextval,'자연맘으로 좋아진 내 피부를 인증하고 상품 받아가세요~',SYSDATE,19.0,'자연맘 어떤 상품을 사용해 보셨나요?<br><br>자연맘으로 좋아진 내 피부를 인증하고 상품 받아가세요~<br>Before와 After 인증샷이 있다면 당첨 확률은 Up!<br>자연맘 피부왕으로 뽑히신 5분께는 <br>10만원 상당의 자연맘 상품을 보내드립니다.<br><br>이벤트 기간 : 3월 10일~ 3월 31일<br><br>많은 참여 부탁드려요^^<br>',0.0,2.0,'admin01');
INSERT INTO tb_event (event_no, evt_title, evt_write_day, evt_hits, evt_content, evt_del_check, board_id, mem_id) VALUES (EVENT_NO_SEQ.nextval,'피부 인증샷',SYSDATE,10.0,'<img src=http://i.imgur.com/xZQ9A66.jpg width=480><br>ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ인증임 상품내놔<br>',0.0,2.0,'soojin');
INSERT INTO tb_event (event_no, evt_title, evt_write_day, evt_hits, evt_content, evt_del_check, board_id, mem_id) VALUES (EVENT_NO_SEQ.nextval,'피부 인증샷2',SYSDATE,10.0,'<img src=http://i.imgur.com/xZQ9A66.jpg width=480><br>ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ또 인증임 상품내놔<br>',1.0,2.0,'soojin');
INSERT INTO tb_event (event_no, evt_title, evt_write_day, evt_hits, evt_content, evt_del_check, board_id, mem_id) VALUES (EVENT_NO_SEQ.nextval,'맑아진 피부, 커진 자신감',SYSDATE,5.0,'너무 좋아요<br>피부 자신감 얻었어요<br>화보도 찍었어요<br>포샵은 조금만 했어요<br><img src=http://i.imgur.com/Is27hIK.jpg width=690><br>',0.0,2.0,'soomin');
INSERT INTO tb_event (event_no, evt_title, evt_write_day, evt_hits, evt_content, evt_del_check, board_id, mem_id) VALUES (EVENT_NO_SEQ.nextval,'자연맘과 함께라면',SYSDATE,16.0,'자연맘 친구가 추천해줘서 사용해봤는데<br>이제 자연맘 비누 없으면 안될거 같아요<br><br>아침마다 화장이 잘 먹어서 기분이 좋네요<br><br><img src=http://i.imgur.com/rbp8HpW.jpg height=575 width=383><br><br>친환경 제품은 역시 달라도 뭐가 다르군요<br>',0.0,2.0,'sora');


-------------------------------------------------------------------- notice
INSERT INTO tb_notice (notice_no, ntc_title, ntc_write_day, ntc_hits, ntc_content, ntc_del_check, ntc_attached_file1, ntc_attached_file2, board_id, mem_id) VALUES (NOTICE_NO_SEQ.NEXTVAL,'자연맘 사이트 오픈을 축하해주세요',SYSDATE,72.0,'<img src=http://i.imgur.com/jhU5RJN.jpg width=299><br>자연맘 사이트가 그랜드 오픈했습니다.<br>이제 온라인으로 친환경 자연맘 비누를 마음껏 구입하실 수 있습니다.<br><br>여러분 축하해주세요 짝짝짝!<br>',0.0,'null','null',1.0,'admin01');
INSERT INTO tb_notice (notice_no, ntc_title, ntc_write_day, ntc_hits, ntc_content, ntc_del_check, ntc_attached_file1, ntc_attached_file2, board_id, mem_id) VALUES (NOTICE_NO_SEQ.NEXTVAL,'설날연휴 휴무안내',SYSDATE,121.0,'<img src=http://i.imgur.com/VIRttJX.jpg width=690><br>',0.0,'null','null',1.0,'admin02');
INSERT INTO tb_notice (notice_no, ntc_title, ntc_write_day, ntc_hits, ntc_content, ntc_del_check, ntc_attached_file1, ntc_attached_file2, board_id, mem_id) VALUES (NOTICE_NO_SEQ.NEXTVAL,' 설날연휴 휴무안내',SYSDATE,2.0,'<img src=http://i.imgur.com/VIRttJX.jpg width=690><br>',1.0,'null','null',1.0,'admin01');
INSERT INTO tb_notice (notice_no, ntc_title, ntc_write_day, ntc_hits, ntc_content, ntc_del_check, ntc_attached_file1, ntc_attached_file2, board_id, mem_id) VALUES (NOTICE_NO_SEQ.NEXTVAL,'자연맘 고객님 배송이 늦어져 정말 죄송합니다.',SYSDATE,70.0,'안녕하세요 자연맘입니다.<br>핑거루트관련 주문 폭주로인하여 핑거루트주문고객 및 일반주문고객님들의<br>배송 및 배송관리가 원활하지 못해<br>고객님께 불편을 끼쳐드리게 된 점 정말 죄송하다는 말씀을 드리고싶습니다.<br>&nbsp;<br>우선, 저희지역쪽 택배물량이 급증하다보니 택배사측(cj대한통운)과도 소통이 지연되어<br>송장번호 입력이 늦어져 발송이 됐음에도 취소를 해드리거나<br>제품이 잘못 발송된 경우가 많을 것이라 예상이됩니다.<br>&nbsp;<br>이에따라 2/29~3/4까지 오배송된 건들의 문의접수를 받고<br>재발송을 해드리려고합니다.<br>&nbsp;<br>자연맘을 믿고 주문해주셨는데 배송이 늦어져 한번,<br>물건이 잘못 발송되어 두번,<br>배송관련 문의 대응부족 세번,<br>여러번 실망하셨을 고객님들께 정말 죄송하다는 말씀을 드립니다.<br>&nbsp;<br>다음주는 전화문의량이 많아 연결이 원활하지 못할것으로 예상됩니다.<br>카카오톡 플러스친구 @자연맘을 등록하여 오배송건들에 대해 문의를 주시면<br>확인 후 최대한 빠른 시일내 제품을 재발송해드리도록 하겠습니다.<br>(@자연맘 검색 시 나오지않으신다면 @자연으로 검색하시면 16번째 @자연맘을 찾으실 수 있으십니다.)<br>&nbsp;<br>이번 핑거루트사태를 계기로 자연맘 구성원들 모두 비상체제로<br>문제점을 개선해나가고 있사오니 조금만 넓은 아량으로 이해해주시면<br>보다 좋은 제품과 서비스로 보답하는 자연맘이 되도록 노력하겠습니다.<br>감사합니다.<br>',0.0,'null','null',1.0,'admin01');



------------------------------------------------------------------------ faq
INSERT INTO tb_faq (faq_no, faq_title, faq_content, faq_del_check, board_id, mem_id) VALUES (FAQ_NO_SEQ.NEXTVAL,'결제 창이 안뜨는데 어떻게 해야하나요?','간혹 결제 창이 안뜬다고 말씀하시는 고객님들이 많으십니다.<br>이 경우 팝업 설정을 차단해놓아서 자동으로 KCP결제 창이 뜨지않기때문에 수동으로 결제창을 열어주셔야합니다.<br>&nbsp;<br>주문결제 시도하셨을때 만약 아래와 같은 화면이 보이신다면 결제하기 버튼을 누르시면 KCP결제 페이지를 보실 수 있으십니다.<br><br><img src=http://i.imgur.com/UdtItem.png width=690><br><br>혹시 위에 사진과 같이 결제하기가 뜨지않고 이상한 문구가 뜨는 경우에는 KCP프로그램이 설치되지않아 발생하는 문제이오니, 결제하는 과정에서 KCP 결제에 필요한 자료를 설치 후 진행해주시기 바랍니다.<br>감사합니다.<br>',0.0,3.0,'admin01');
INSERT INTO tb_faq (faq_no, faq_title, faq_content, faq_del_check, board_id, mem_id) VALUES (FAQ_NO_SEQ.NEXTVAL,'결제 창이 안뜨는데 어떻게 해야하나요?','간혹 결제 창이 안뜬다고 말씀하시는 고객님들이 많으십니다.<br>이 경우 팝업 설정을 차단해놓아서 자동으로 KCP결제 창이 뜨지않기때문에 수동으로 결제창을 열어주셔야합니다.<br>&nbsp;<br>주문결제 시도하셨을때 만약 아래와 같은 화면이 보이신다면 결제하기 버튼을 누르시면 KCP결제 페이지를 보실 수 있으십니다.<br><br><img src=http://i.imgur.com/UdtItem.png width=690><br><br>혹시 위에 사진과 같이 결제하기가 뜨지않고 이상한 문구가 뜨는 경우에는 KCP프로그램이 설치되지않아 발생하는 문제이오니, 결제하는 과정에서 KCP 결제에 필요한 자료를 설치 후 진행해주시기 바랍니다.<br>감사합니다.<br>',1.0,3.0,'admin01');
INSERT INTO tb_faq (faq_no, faq_title, faq_content, faq_del_check, board_id, mem_id) VALUES (FAQ_NO_SEQ.NEXTVAL,'빨리 배송받는 방법을 알려주세요','오전 11시까지 주문/결제를 완료하시면<br>다음날 바로 상품을 배송 받으실 수 있습니다.<br>',0.0,3.0,'admin01');
INSERT INTO tb_faq (faq_no, faq_title, faq_content, faq_del_check, board_id, mem_id) VALUES (FAQ_NO_SEQ.NEXTVAL,'빨리 배송받는 방법을 알려주세요','오전 11시까지 주문/결제를 완료하시면<br>다음날 바로 상품을 배송 받으실 수 있습니다.<br>',1.0,3.0,'admin01');
INSERT INTO tb_faq (faq_no, faq_title, faq_content, faq_del_check, board_id, mem_id) VALUES (FAQ_NO_SEQ.NEXTVAL,'제품은 어떻게 보관해야 하나요?','저희 자연맘 제품은 원재료 외엔 첨가된 것이 없어 보관을 잘못하실 경우<br>변질되거나 벌레가 생길 수 있으니 보관에 주의하시기 바랍니다.<br>직사광선 및 습기를 피해 건냉한 곳에 보관하시고 냉장 또는 냉동보관 하시는 것이 좋습니다.<br>',0.0,3.0,'admin01');
INSERT INTO tb_faq (faq_no, faq_title, faq_content, faq_del_check, board_id, mem_id) VALUES (FAQ_NO_SEQ.NEXTVAL,'정말 국내산이 맞나요?','조금만 살펴보면 알 수 있는 약초 등은 이미지로 비교하시면 쉽게 알 수 있고<br>구분이 어려운 한방차 등을 전문적으로 취급하시는 분이라면 어렵지 않게 구별하실 수 있습니다.<br>그리고, 수많은 경쟁업체들이 주시하고 있으며 소비자인양 구매를 해서 원산지 허위표시를<br>신고하기 때문에 더욱 철저하게 확인을 하고 있습니다.<br>저희 자연맘은 고객님들의 신뢰를 위해 원산지, 생산자 표기를 하여 보내드리고 있습니다.<br>',0.0,3.0,'admin01');



