DROP VIEW V_EVENT_LIST;


CREATE VIEW V_EVENT_LIST AS
SELECT e.EVENT_NO, e.EVT_TITLE, e.MEM_ID, e.EVT_WRITE_DAY, e.EVT_HITS, e.EVT_CONTENT,
NVL((SELECT COUNT(re.EVENT_RE_NO) FROM TB_EVENT_RE re WHERE re.EVT_NO = 
e.EVENT_NO AND re.EVT_RE_DEL_CHECK = 0), 0) as count_re
FROM TB_EVENT e LEFT OUTER JOIN TB_EVENT_RE r
ON (e.EVENT_NO = r.EVT_NO)
WHERE e.EVT_DEL_CHECK =0 
GROUP BY e.EVENT_NO, e.EVT_TITLE, e.MEM_ID, e.EVT_WRITE_DAY, e.EVT_HITS, e.EVT_CONTENT
ORDER BY e.EVENT_NO ASC;


UPDATE "NMDB"."TB_MEMBER" SET MEM_ADDR_DETAIL = '서울시 용산구 후암동@406-7번지 상원빌2차' WHERE MEM_ID='admin01';
UPDATE "NMDB"."TB_MEMBER" SET MEM_ADDR_DETAIL = '충청남도 아산시 대방읍 장재리@용연마을 감자하우스' WHERE MEM_ID='admin02';
UPDATE "NMDB"."TB_MEMBER" SET MEM_ADDR_DETAIL = '서울시 강동구 강동3동 강동아파트@102동 202호' WHERE MEM_ID='soomin';
UPDATE "NMDB"."TB_MEMBER" SET MEM_ADDR_DETAIL = '서울시 광진구 구의2동 구의아파트@101동 202호' WHERE MEM_ID='sora';
UPDATE "NMDB"."TB_MEMBER" SET MEM_ADDR_DETAIL = '경기도 안산시 안산구 안산3동@안산아파트 403동 101호' WHERE MEM_ID='soojin';
UPDATE "NMDB"."TB_MEMBER" SET MEM_ADDR_DETAIL = '경기도 남양주시 양주동 남양주아파트@303동 202호' WHERE MEM_ID='minhee';

UPDATE TB_MEMBER SET MEM_GENDER=2 WHERE MEM_GENDER=0;